//! Shared core types for the Rust OpenSearch-compatible node.

pub mod version;

pub use version::{
    Version, OPENSEARCH_2_10_0, OPENSEARCH_2_17_0, OPENSEARCH_2_18_0, OPENSEARCH_2_7_0,
    OPENSEARCH_2_9_0, OPENSEARCH_3_0_0, OPENSEARCH_3_6_0, OPENSEARCH_3_7_0,
    OPENSEARCH_3_7_0_MIN_COMPAT_TRANSPORT, OPENSEARCH_3_7_0_TRANSPORT,
    OPENSEARCH_DISCOVERY_NODE_STREAM_ADDRESS,
};
