[package]
name = "os-engine-tantivy"
version = "0.2.1"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
os-engine = { path = "../os-engine" }
os-plugin-knn = { path = "../os-plugin-knn" }
os-query-dsl = { path = "../os-query-dsl" }
regex = "1"
serde = { workspace = true }
serde_json.workspace = true
tantivy = "=0.21.1"
time = "=0.3.36"

[[bench]]
name = "deterministic_baselines"
path = "benchmarks/deterministic_baselines.rs"
harness = false
