[package]
name = "os-transport"
version = "0.2.3"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
flate2.workspace = true
os-core = { path = "../os-core" }
os-engine = { path = "../os-engine" }
os-stream = { path = "../os-stream" }
os-wire = { path = "../os-wire" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
base64.workspace = true

[[bin]]
name = "refresh-wire-benchmark"
path = "benchmarks/refresh_wire.rs"

[[bin]]
name = "get-wire-benchmark"
path = "benchmarks/get_wire.rs"

[[bin]]
name = "multi-get-wire-benchmark"
path = "benchmarks/multi_get_wire.rs"

[[bin]]
name = "index-wire-benchmark"
path = "benchmarks/index_wire.rs"

[[bin]]
name = "update-wire-benchmark"
path = "benchmarks/update_wire.rs"

[[bin]]
name = "bulk-wire-benchmark"
path = "benchmarks/bulk_wire.rs"

[[bin]]
name = "delete-wire-benchmark"
path = "benchmarks/delete_wire.rs"
